name: DevSecKit Security Analysis

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: "Security analysis type"
        required: true
        type: choice
        options:
          - sast
          - sca
          - secrets
          - iac
          - dast
          - iast
      target:
        description: "Scan target path (or URL for dast/iast)"
        required: true
        default: "."

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make scanner scripts executable
        run: chmod +x scanners/**/**/*.sh

      - name: Run SAST
        if: ${{ github.event.inputs.scan_type == 'sast' }}
        run: scanners/sast/semgrep.sh ${{ github.event.inputs.target }} reports/semgrep.json

      - name: Run SCA
        if: ${{ github.event.inputs.scan_type == 'sca' }}
        run: scanners/sca/dependencycheck.sh ${{ github.event.inputs.target }} reports

      - name: Run Secrets Scan
        if: ${{ github.event.inputs.scan_type == 'secrets' }}
        run: scanners/secrets/gitleaks.sh ${{ github.event.inputs.target }} reports/gitleaks.json

      - name: Run IaC Scan
        if: ${{ github.event.inputs.scan_type == 'iac' }}
        run: scanners/iac/checkov.sh ${{ github.event.inputs.target }} reports/checkov.json

      - name: Run DAST
        if: ${{ github.event.inputs.scan_type == 'dast' }}
        run: scanners/dast/zap.sh ${{ github.event.inputs.target }} reports/zap.json

      - name: Run IAST-lite
        if: ${{ github.event.inputs.scan_type == 'iast' }}
        run: scanners/iast/iast.sh ${{ github.event.inputs.target }} reports/iast-lite.json

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devseckit-reports
          path: reports/
